version: '3.8'

services:
  cleanarchitecture.webapi:
    image: ${DOCKER_REGISTRY-}cleanarchitecture
    container_name: cleanarchitecture
    build:
      context: .
      dockerfile: src/WebApi/Dockerfile
    environment: 
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT:-Production}
    ports:
      - "8100:8080"
      - "8101:8081"
    networks:
      - cleanarchitecture-network
    depends_on:
      - cleanarchitecture.db
      - cleanarchitecture.redis
      - cleanarchitecture.seq

  cleanarchitecture.db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: cleanarchitecture-db
    environment:
      SA_PASSWORD: "cleanarchitecture@2025"
      ACCEPT_EULA: "Y"
    volumes:
      - mssql-data:/var/opt/mssql
    ports:
      - "7102:1433"
    networks:
      - cleanarchitecture-network

  cleanarchitecture.redis:
    image: redis:alpine
    container_name: cleanarchitecture-redis
    restart: always
    volumes:
      - redis-data:/data
    ports:
      - "8103:6379"
    networks:
      - cleanarchitecture-network

  cleanarchitecture.seq:
    image: datalust/seq:latest
    container_name: cleanarchitecture-seq
    environment:
      - ACCEPT_EULA=Y
    ports:
      -  "5342:5341"
      -  "8104:80"
    networks:
      - cleanarchitecture-network

networks:
  cleanarchitecture-network:

volumes:
  mssql-data:
  redis-data:
